# This is a basic workflow to help you get started with Actions

name: CI

# Contro  ls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore:
    - '**/*.md'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build .zip file
        run: |
         zip -r /$GITHUB_WORKSPACE/test.zip ./test/*
         zip -r /$GITHUB_WORKSPACE/test2.zip ./test/*
         ls

      - name: Delete latest Release
        uses: Janus451/delete_last_release@v1.5
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
         
         
      # See: https://github.com/actions/upload-release-asset
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        with:
          tag_name: "latest"
          release_name: "latest"
          prerelease: false
      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
        with:   
          upload_url: ${{ steps.create_release.outputs.upload_url}}
          asset_path: ./test.zip 
          asset_name: test.zip
          asset_content_type: application/zip
      - name: Upload Release Asset2
        id: upload_release_asset2
        uses: actions/upload-release-asset@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          upload_url: ${{ steps.create_release.outputs.upload_url}}
          asset_path: ./test2.zip 
          asset_name: test2.zip
          asset_content_type: application/zip  

      
